ARG MYSQL_VERSION=5.7.38

# see https://hub.docker.com/_/mysql/
FROM mysql:${MYSQL_VERSION}

LABEL maintainer="purelib-mysql-base <lewis_dev@163.com>" version="1.0" license="MIT" app.name="purelib-mysql"

## 允许空密码
# ENV MYSQL_ALLOW_EMPTY_PASSWORD yes